container:
  image: cirrusci/flutter:latest
  cpu: 8
  memory: 16G

check_code_style_task:
  flutter_doctor_script: flutter doctor
  flutter_analyze_script:
    - cd flutter_app
    - flutter packages get
    - flutter packages pub run build_runner build --delete-conflicting-outputs
    - flutter analyze